/*Scrips ORM owner*/

/************TABLAS DE OPT-ORM*****************/
SELECT * FROM OPT_CONSULTA;
SELECT * FROM OPT_DIRECTORIO;
SELECT * FROM OPT_LAYOUT;
SELECT * FROM OPT_PIVOT;
SELECT * FROM OPT_PAGESETTINGS;
SELECT * FROM OPT_PARAMETROS;


/***********SE DEBE MIGRAR *******************/
--1.Consulta 
--2.Directorio
--3.layout
--4.pivot
--5.pagesettings
--6.parametros
/********************************************/




