REM INSERTING into OPT_DIRECTORIO
SET DEFINE OFF;
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80000','Recaudos','0');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80001','Cupon','80000');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80013','Presentación','80000');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80022','Conciliacion vs Transacción','80000');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80043','Datos Perfil','80000');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80104','Consumos Liquidados','80006');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80121','CEO_InterfazContable ','0');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80131','Sobrantes y Faltantes','80000');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80135','Facturación en Sitio','80006');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80147','JENIFER PEJENDINO','80058');
Insert into OPT_DIRECTORIO (ID_DIRECTORIO,NOMBRE,ID_DIR_PADRE) values ('80155','Conciliación Saldos a Favor','80151');
/